packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  esbuild: false
  msgpackr-extract: false
  msw: false
  prisma: true

overrides:
  typescript: "5.9.2"
  react: "19.2.3"
  react-dom: "19.2.3"
  "@types/react": "19.2.3"
  "@types/react-dom": "19.2.3"
