// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: string;
  email: string;
  password: string;
  createdAt: Date;
  updatedAt: Date;
  todos?: Todo[];
  projects?: Project[];
  runners?: Runner[];
  vacancies?: UserVacancy[];
}

export interface Project {
  id: string;
  externalId: string | null;
  description: string | null;
  name: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
  todos?: Todo[];
}

export interface Runner {
  id: string;
  name: string;
  type: string;
  enabled: boolean;
  schedule: string | null;
  config: JsonValue;
  lastRunAt: Date | null;
  status: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
}

export interface Todo {
  id: string;
  externalId: string | null;
  externalSource: string | null;
  title: string;
  description: string;
  tags: string[];
  priority: boolean;
  date: string;
  time: string;
  endDate: string;
  repeat: string | null;
  dependsOn: string[];
  done: boolean;
  doneDate: string;
  userId: string;
  projectId: string | null;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
  project?: Project | null;
}

export interface Vacancy {
  id: string;
  company: string;
  title: string;
  publishedAt: string;
  externalId: string;
  externalSource: string;
  description: string;
  area: string | null;
  url: string;
  salary: string | null;
  keywords: string[];
  createdAt: Date;
  updatedAt: Date;
  users?: UserVacancy[];
}

export interface UserVacancy {
  userId: string;
  vacancyId: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  user?: User;
  vacancy?: Vacancy;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
